### ISSUE TITLE
Why upon launch, this app removes xinput1_3.dll?

### ISSUE THREAD

**Issue by RedAISkye** [TekkaGB/Unverum#25]
After hitting launch to apply the mods, for some reason, it's removing the file "xinput1_3.dll" from the location "RED\Binaries\Win64\".

I tried to set the file to Read-only but then it throws the error of "Access to path is denied".

Why is it trying to remove that file? I need it for my x360ce to work.

**Comment by TekkaGB** [comment]
I assumed that only UnrealModLoader utilized that dll and deleted it and copied it back over whenever an UnrealModLoader is used. I can stop deleting it but keep in mind it will still be replaced if an UnrealModLoader mod is used
