### ISSUE TITLE
Alphanumerical sorting weird behaviour

### ISSUE THREAD

**Issue by fsavariano** [TekkaGB/Unverum#28]
This is a minor, but rather annoying bug. As of one of the latest updates, each time I open Unverum, mods get sorted as if 10, 100  or whatever number starting with 1 was greater than 2 (as a string, rather than a number). If I order clicking on "name" it sorts normally, but when restarting, same thing happens again. This is annoying for me because I have every skin mod ordered by palette slot.

**Comment by TekkaGB** [comment]
Fixed in https://github.com/TekkaGB/Unverum/commit/7fe24615d3502a0df5b81bbc2e62696e78564dd4
