### ISSUE TITLE
Unable to update Unverum to 2.2.0

### ISSUE THREAD

**Issue by silverrose99** [TekkaGB/Unverum#29]
When Unverum starts up its gives me a prompt to update Unverum to the latest version(2.2.0). I click "yes" and it proceeds to update the app like usual. After it finishes downloading the update a notification text box appears saying "Finished downloading unverum_8ba9d.7z!Unverum will now restart." I press ok, but it doesn't restart. I then see this:
![unverum update error](https://user-images.githubusercontent.com/109921023/180662963-a3b75ed4-cae4-4b79-adf7-c66c272eaffb.png)
Is there any fix to this?

**Comment by TekkaGB** [comment]
Download the latest release and replace your current files with its contents. Seems like you're on version 2.0.1 and I fixed this issue on 2.0.2
