### ISSUE TITLE
Show FileName in metadata for downloaded mods

### ISSUE THREAD

**Issue by xpire** [TekkaGB/Unverum#30]
I use this mod downloader for guilty gear, and am really impressed with this app. However, when I download a mod for a specific Skin Slot, I have no way of knowing what slot each skin goes in. I would like for the metadata that appears when you click on a downloaded mod (That shows Submitter, Category and Home page) to also show filename and or any other useful identifying metadata for that file. 

I've looked at the source code and am happy to contribute a PR to provide this feature.

The Filename is already part of the API code in `GameBananaStructures.cs` [here](https://github.com/TekkaGB/Unverum/blob/master/Unverum/Structures/GameBananaStructures.cs#L47).

The Filename is stored in a private variable in `ModDownloader.cs` [here](https://github.com/TekkaGB/Unverum/blob/master/Unverum/ModDownloader.cs#L26), so it should be really easy to store the filename in the `Metadata` [object](https://github.com/TekkaGB/Unverum/blob/master/Unverum/ModDownloader.cs#L195).

Happy to hear more thoughts about this.

**Comment by TekkaGB** [comment]
The filename does not always indicate all of this information. You can just rename the mod to indicate which skin slot it takes by right clicking it.

**Comment by xpire** [comment]
I understand that it is not bullet proof, but currently we can download two different files from the exact same mod and have Unverum not knowing that they are different. We can even download the same mod twice, however then we can just delete the duplicate. The thing is we don't know how to differentiate between different file IDs of mods, so I think having a unique identifier for each mod would be useful in telling the user what mod they used if they ever download a mod and then forget to rename it. 

I was looking at the API output, and I saw that there are more fields we could use, like the [description](https://github.com/TekkaGB/Unverum/blob/master/Unverum/Structures/GameBananaStructures.cs#L58), which we could show instead of the filename, but I think showing both covers almost all cases of what I'm talking about. A more complicated solution could also be to show metadata in the table so users can choose not to see the filename or description column if they think its clutters the UI.

For example, I feel like some of the following fields would be pretty useful if we could see it in Unverum:

```
 {
            "_idRow": "658692",
            "_sFile": "color_06_6ea50.rar",
            "_sDescription": "Goes over color 06",
        ...
},
```

**Comment by TekkaGB** [comment]
Added just the file description in the metadata in https://github.com/TekkaGB/Unverum/commit/a20164beecc5396b7c77b9f45e19a3b916b28bed
