### ISSUE TITLE
Auto Update function populating incorrect metadata and leaves messes after updating.

### ISSUE THREAD

**Issue by Walnut356** [TekkaGB/Unverum#6]
This has been happening for several versions, but the auto update button will populate mismatching information. The popup asking to update will have 1 set of metadata, the header of the "select which file" will have a different mod name, and then the files i can choose from are clearly the files for 3rd mod. All 3 mods are ones i have installed, but it should still populate the correct metadata regardless. This has happened with a bunch of different mods, all 1 click installed through gamebanana, and then slightly renamed to include sorting tags (e.g. "[JKO] (slot 1) mod name"). 

Additionally, the auto update feature sometimes does not delete old files after installing new ones. This leads to situations where a mod can end up hidden inside another mod folder, and I have to go in through the individual folders, find it, and delete it to actually get rid of it. It's probably related to the above issue, but I honestly don't really know. It looks like many of the ones i deleted were offset by 1 folder - keep in mind, with my sort tags, everything is in a precise order (e.g. [JKO] (slot 9) was also in the folder for [JKO] (slot 8))

![image](https://user-images.githubusercontent.com/39544927/132117986-300bc654-fe12-4bd4-a7b2-973d0b5b1312.png)

Checking the mod json file, all the data within it is correct for the faust sound mod, so i don't even know how the gio mod ended up there

Confirmation that these were also being loaded into strive incorrectly:

![image](https://user-images.githubusercontent.com/39544927/132118606-9b817a9e-bf8e-48cc-8c3e-ee3d8efd0089.png)

Edit: After  cleaning up the extra files that were hanging around, it looks like my updates no longer have this issue? I'm unsure how it managed to happen in the first place, but having some sort of warning or something to clue the user in to delete extraneous files would be dope

Nvm, it can happen when the updated file is packed differently than the original file, for example if one is in a sub folder and one isn't. It doesn't replace/remove the old files properly since it's probably just trying to overwrite whatever's there

Example:

![image](https://user-images.githubusercontent.com/39544927/132427387-89885295-9eb3-4f67-8d14-963191a1e948.png)

**Comment by TekkaGB** [comment]
Hopefully addressed in https://github.com/TekkaGB/Unverum/commit/6654882b5ffef74222a87327ee9ac61216560f42, had a ClearDirectory function but never called it when updating mods
