### ISSUE TITLE
Dont start with "launch trough steam" option [Sparking Zero]

### ISSUE THREAD

**Issue by Ububacka** [TekkaGB/Unverum#65]
![Screenshot 2024-10-11 204414](https://github.com/user-attachments/assets/ecdf27d2-eea2-4350-8388-de3efc5e652f)

Is it supposed to look like that while trying to open it with the launch steam options?

Maybe I'm stupid, but unversum just starts the game with the executable option.

**Comment by TekkaGB** [comment]
Fixed in https://github.com/TekkaGB/Unverum/releases/tag/2.6.1
