### ISSUE TITLE
Sort by name sorts numbers incorrectly 

### ISSUE THREAD

**Issue by Walnut356** [TekkaGB/Unverum#7]
See below. Expected result should have 10 and 11 after 7, but the sort function places them in-between 1 and 2. Sorting by ASCII values maybe? http://www.davekoelle.com/alphanum.html

![image](https://user-images.githubusercontent.com/39544927/132118332-03d2afae-b051-42ce-a80b-58fb66804ed0.png)

Compared to default "Sort by name" in windows finder:

![image](https://user-images.githubusercontent.com/39544927/132118363-ced50ad3-db16-4aa3-947e-c18b5d00219f.png)

**Comment by TekkaGB** [comment]
Addressed in https://github.com/TekkaGB/Unverum/commit/4f0423ffeb86cd57f301eaa4106ece8ac36db11a, will be available in next update
